### ISSUE TITLE
count from 2024 data is all empty ...

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/coexistBCforests#2]
@wangxm-forest @christophe-rd @DeirdreLoughnan I am struggling to understand the 2024 data we collected in Smithers, and perhaps also the structure of the data folder here. I was looking at this [file](https://github.com/temporalecologylab/coexistBCforests/blob/master/Data/Janzen-Connell/SeedlingDATA2020_2024.xlsx) where the count column for what I assume is the 2024 data is all empty. 

1. What does this mean when the rest of the entries are always 0 or 1? I am also wondering the following now.
2. Why are there two identically named folders in data? See [here](https://github.com/temporalecologylab/coexistBCforests/tree/master/Data)?
3. Is this the original 2024 data [here](https://github.com/temporalecologylab/coexistBCforests/blob/0ef270d70318ccc01ed9c685cbe74a5b7f72d53a/Data/Janzen-Connell/SeedlingDATA2024.csv)? If so, what is the xlsx sheet for (and again, why is this all empty for count for most of 2024)? If not, what is the structure for adding new data each year?

Any help would be much appreciated so I can understand things here!

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver 
> 1. What does this mean when the rest of the entries are always 0 or 1? I am also wondering the following now.

It is just an omission in the data entry. My understanding was that this column is essentially the presence/absence of this seedling at the end of a given year. So all new observations should have a count of 1. I am pushing updated files with it entered.

> 2. Why are there two identically named folders in data? See [here](https://github.com/temporalecologylab/coexistBCforests/tree/master/Data)?

I removed the duplicated one. 

> 3. Is this the original 2024 data [here](https://github.com/temporalecologylab/coexistBCforests/blob/0ef270d70318ccc01ed9c685cbe74a5b7f72d53a/Data/Janzen-Connell/SeedlingDATA2024.csv)? If so, what is the xlsx sheet for (and again, why is this all empty for count for most of 2024)? If not, what is the structure for adding new data each year?

Both files are the save, just one saved as a csv. I don't think we ever had a structure for adding the data beyond making sure it gets entered in a timely manner and all datasheets get scanned/photographed in the field. I started including multiple years of height data in one file/datasheet in 2023 as it is helpful in the field to have previous years data to differentiate individuals that are growing close together or when toothpicks are found scattered on the ground. But we always make note of this in the notes column.

**Comment by lizzieinvancouver** [comment]
> I started including multiple years of height data in one file/datasheet in 2023 as it is helpful in the field to have previous years data to differentiate individuals that are growing close together or when toothpicks are found scattered on the ground. But we always make note of this in the notes column.

Okay! This makes sense to me now. I was thinking a better way to format would be to have year as a column and make the data fully long, but I can see how seeing the year before would be very handy so this works. I am closing out this issue since it seems fixed. Thank you!
