### ISSUE TITLE
getting dataCleaningDemography.R to run

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/coexistBCforests#3]
@DeirdreLoughnan Thank you for your great work on the bc Smithers data! I am only getting stuck on running dataCleaningDemography.R ... I get the following error running madNo:

```
> madNo <- aggregate(mad [c("count")],
+                    mad[c("plotGerm")],
+                    FUN = sum)
Error in `[.data.frame`(mad, c("plotGerm")) : undefined columns selected
```

Here's the top of mad:

```
> head(mad)
   Site Plot Sub_plot Height_2020 Height_2021 Height_2022 Height_2023 Distance.to.Conspecific Germinant_ID Count_2020
4  JCMH    1        C          19         MAD         MAD         MAD                   110.5       ABILAS          1
6  JCMH    1        E         710         MAD        <NA>        <NA>                   110.0       ABILAS          1
8  JCMH    2        A          45         MAD        <NA>        <NA>                    95.0       ABILAS          1
13 JCMH    2        E          22         MAD         MAD         MAD                   100.0       ABILAS          1
16 JCMH    2        F          16         MAD        <NA>        <NA>                    26.0       ABILAS          1
18 JCMH    2        F          30         MAD        <NA>        <NA>                    25.0       ABILAS          1
   Count_2021 Count_2022 Count_2023  Tooth.Pick  X                      Note count
4           0          0          0 white heart NA                      <NA>     1
6           0          0          0  blue heart NA tag was out of the ground     1
8           0          0          0   red club  NA                      <NA>     1
13          0          0          0 blue heart  NA                      <NA>     1
16          0          0          0 orange club NA                      <NA>     1
18          0          0          0   red heart NA                      <NA>     1
```

I cannot figure what `plotGerm` should be so any help would be much appreciated!

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver 
It looks like plotGerm gets made on line 97 in the change dataframe. I think I made it to try and determine in what plots a germinant has survived for ever year. In retrospect, I am not sure how useful it really is.

I would be happy to chat about this when we meet Monday as well if helpful.

**Comment by lizzieinvancouver** [comment]
> It looks like plotGerm gets made on line 97 in the change dataframe. I think I made it to try and determine in what plots a germinant has survived for ever year. In retrospect, I am not sure how useful it really is.

Thanks @DeirdreLoughnan ... can you confirm the code is running for you? I had to add ggplot2 to get it to run for me, so I wanted to confirm all of it runs for you before I try to update it to make it run.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan The code is running for me now, thank you!
